Lambda-School-Labs/quake-fe-pt9

quake/src/App.css
quake/src/App.js
quake/src/App.test.js
quake/src/components/Contact.js
quake/src/components/Footer.js
quake/src/components/Header.js
quake/src/components/Home.js
quake/src/components/Login.js
quake/src/components/Login.spec.js
quake/src/components/Nav.js
quake/src/components/Register.js

home page, header and footer

---

package.json
src/App.css
src/components/WorldMap.js
yarn.lock

Axios on map

---

src/components/Login.js
src/components/Register.js

updated endpoints

---

src/components/Login.js
src/components/Register.js

fixed a little mistake

---

src/components/Login.js
src/components/Register.js

change to https

---

src/components/Register.js

changed to https

---

package.json
src/App.css
src/App.js
src/components/Dashboard.js
src/components/Home.js
src/components/Login.js
src/components/Register.js

Ryan dashboard

---

package.json
src/App.css
src/App.js
src/components/Dashboard.js
src/components/Home.js
src/components/LocalMap.js
src/components/Login.js
src/components/Nav.js
src/components/Register.js
src/components/Search.js
src/components/WhatToDo.js

Ryan what to do

---

package.json
src/App.css
src/App.js
src/components/Dashboard.js
src/components/Dropdown.js
src/components/Dropdown2.js
src/components/Fema.js
src/components/Home.js
src/components/LocalMap.js
src/components/Login.js
src/components/Nav.js
src/components/Register.js
src/components/Search.js
src/components/WhatToDo.js

Ryan dropdown

---

src/components/WorldMap.js

update to new earthquake database url.

---

src/components/LeafletMap.js
src/components/Search.js

Searching now zooms depending on the type of place found. Place includes postal codes. invalid place alerts the user.

Zoom based on searched place type.

---

src/components/Login.js
src/components/Register.js

Update in accord with updates on backend.

Update auth url

---

src/components/Home.js
src/components/Login.js
src/components/Register.js

Fixed state change on auth res.

---

src/components/Prepare.js

didnt change heroku

---

src/components/Home.js
src/components/Legend.css
src/components/Legend.js

A map legend to make the data visualization clear to users.

create basic legend.

---

src/components/Home.js
src/components/LeafletMap.js

Map snaps back now when users pan out of bounds of the quake markers.

fixed out of bounds bug

---

package.json
src/components/Eroute.js
src/components/Home.js
src/components/Legend.css
src/components/Legend.js
yarn.lock

add react-render-html to handle data coming from a flask app.

Renderhtml

---

src/App.css
src/components/Header.js
src/components/Home.js
src/components/LeafletMap.js
src/components/Legend.css
src/components/Login.css
src/components/Login.js
src/components/Prepare.css
src/components/Prepare.js
src/components/Register.css
src/components/Register.js

Smoothed out the styling across the app.

color scheme changes

---

src/components/LeafletMap.js

zoom fixed.

---

.codeclimate.yml
README.md

add yml file.

---

.github/workflows/ci.yml

add github workflow file.

---

package.json

add coverage script.

---

src/components/LeafletMap.spec.js
src/components/Login.spec.js
src/components/Nav.spec.js

Adding test for the Nav component and skeleton for tests on the LeafletMap. Just want to see how this works and affects Code Climate.

Added test for Nav component

---

src/App.css
src/components/Home.js
src/components/Prepare.css
src/components/Prepare.js

adjust text size and width.
